import Head from 'next/head';

import { ChatView } from '@/components/ChatView';
import { Header } from '@/components/Header';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'min-h-screen border-2 border-purple-600'}>
        <Header />
        <ChatView />
      </main>
    </>
  );
}
